name: ComplexProficiencies
version: ${project.version}
main: com.miketheshadow.complexproficiencies.ComplexProficiencies
api-version: 1.13
authors: [MikeTheShadow]
description: Creates complex proficiencies For MC.
depend: [NBTAPI]
commands:
  opengui:
    description: Displays a craftingui gui
    usage: /<craftingui> [GUI Name]
    permission: ComplexProficiencies.gui
    permission-message: You don't have ComplexProficiencies.gui permission
  getitemtags:
    description: Gets the type as a string of an item
    usage: /<getitemtype>
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission
  addrecipe:
    description: add a recipe to a prof
    usage: /<addrecipe> [level req] [experience amount] [gui name] [proffession]
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission
  addcategory:
    description: add a prof category
    usage: /<addcategory> [name]
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission
  removecategory:
    description: remove a prof category
    usage: /<removecategory> [name]
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission
  addsubcategory:
    description: add a sub category to a base category
    usage: /<addsubcategory> [Base Category]
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission
