name: ComplexProficiencies
version: ${project.version}
main: com.miketheshadow.complexproficiencies.ComplexProficiencies
api-version: 1.13
authors: [MikeTheShadow]
description: Creates complex proficiencies For MC.
depend: [NBTAPI]
commands:
  craftinggui:
    description: Displays a craftingui gui
    usage: /<craftingui> [GUI Name]
    permission: ComplexProficiencies.gui
    permission-message: You don't have ComplexProficiencies.gui permission
  getitemtype:
    description: Gets the type as a string of an item
    usage: /<getitemtype>
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission
  addrecipe:
    description: add a recipe to the plugin
    usage: /<addrecipe>
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission