name: ComplexProficiencies
version: ${project.version}
main: com.miketheshadow.complexproficiencies.ComplexProficiencies
api-version: 1.13
authors: [MikeTheShadow]
description: Creates complex proficiencies For MC.
depend: [NBTAPI,WorldGuard,XPBoost,Vault,Duels]
commands:
  getitemtags:
    description: Gets the type as a string of an item
    usage: /<getitemtype>
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission
  labor:
    description: Displays current user labor
    usage: /<labor>
    permission: ComplexProficiencies.basic
    permission-message: You don't have ComplexProficiencies.basic permission
  resetdb:
    description: wipe the database for Complex Proficiencies
    permission: ComplexProficiencies.danger
    permission-message: You don't have UNKNOWN_PERMISSION
  prof:
    description: Gets a users level in a prof
    usage: /<prof> [profname] [player]
    permission: ComplexProficiencies.basic
    permission-message: You don't have ComplexProficiencies.basic permission
  proftop:
    description: Gets the top users in a prof
    usage: /<proftop> [profname]
    permission: ComplexProficiencies.experimental
    permission-message: You don't have ComplexProficiencies.experimental permission
  caravancreate:
    description: Creates a caravan with a specific loadout
    usage: /<caravancreate> [moneyCost] [location] [playerName]
    permission: ComplexProficiencies.experimental
    permission-message: You don't have ComplexProficiencies.experimental permission
  caravanreturn:
    description: Turns in a caravan for a specific value
    usage: /<caravanreturn> [location] [playerName]
    permission: ComplexProficiencies.experimental
    permission-message: You don't have ComplexProficiencies.experimental permission
  cver:
    description: Check the current version of the plugin
    usage: /<cver>
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission
  cremoveplayer:
    description: Remove player from complex profs
    usage: /<complexremoveplayer> [name]
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission
  caddlabor:
    description: Adds labor to a user
    usage: /<caddlabor> [name] [amount]
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission
  claborreset:
    description: Resets labor of the entire server
    usage: /<claborreset>
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission
  capi:
    description: interact with the complex API
    usage: /<capi> [command]
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission
  cdata:
    description: interact with the complex API
    usage: /<cdata> [command]
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission
  cdebug:
    description: A debug command to display internal info
    usage: /<cdebug>
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission
#USER STAT STUFF
  userstats:
    description: Gets yours/a users current stats.
    usage: /<userstats> [player]
    permission: ComplexProficiencies.misc
    permission-message: You don't have ComplexProficiencies.misc permission
  mystats:
    description: Gets your current stats.
    usage: /<mystats>
    permission: ComplexProficiencies.basic
    permission-message: You don't have ComplexProficiencies.basic permission
  fixexperience:
    description: Updates all current players experience to match that of the leveling system.
    usage: /<fixexperience>
    permission: ComplexProficiencies.levelAdmin
    permission-message: You don't have ComplexProficiencies.levelAdmin permission
  setexperience:
    description: Sets the experience of a player.
    usage: /<setexperience> [player] [Amount]
    permission: ComplexProficiencies.levelAdmin
    permission-message: You don't have ComplexProficiencies.levelAdmin permission
  setlevel:
    description: Sets the level of a player.
    usage: /<setlevel> [player] [Amount]
    permission: ComplexProficiencies.levelAdmin
    permission-message: You don't have ComplexProficiencies.levelAdmin permission
  addexperience:
    description: Adds experience to the select player.
    usage: /<addexperience> [player] [Amount]
    permission: ComplexProficiencies.levelAdmin
    permission-message: You don't have ComplexProficiencies.levelAdmin permission
  addpartyexperience:
    description: Adds experience to the party.
    usage: /<addpartyexperience> [player] level [levelNumber]
    permission: ComplexProficiencies.levelAdmin
    permission-message: You don't have ComplexProficiencies.levelAdmin permission