name: ComplexProficiencies
version: ${project.version}
main: com.miketheshadow.complexproficiencies.ComplexProficiencies
api-version: 1.13
authors: [MikeTheShadow]
description: Creates complex proficiencies For MC.
depend: [NBTAPI,WorldGuard,XPBoost,Vault,Duels]
commands:
  opengui:
    description: Displays a craftingui gui
    usage: /<craftingui> [GUI Name]
    permission: ComplexProficiencies.gui
    permission-message: You don't have ComplexProficiencies.gui permission
  getitemtags:
    description: Gets the type as a string of an item
    usage: /<getitemtype>
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission
  addrecipe:
    description: add a recipe to a prof
    usage: /<addrecipe> [level req] [experience amount] [gui name] [proffession]
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission
  addcategory:
    description: add a prof category
    usage: /<addcategory> [name]
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission
  removecategory:
    description: remove a prof category
    usage: /<removecategory> [name]
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission
  addsubcategory:
    description: add a sub category to a base category
    usage: /<addsubcategory> [Base Category]
    permission: ComplexProficiencies.admin
    permission-message: You don't have ComplexProficiencies.admin permission
  labor:
    description: Displays current user labor
    permission: ComplexProficiencies.basic
    permission-message: You don't have ComplexProficiencies.basic permission
  resetdb:
    description: wipe the database for Complex Proficiencies
    permission: ComplexProficiencies.danger
    permission-message: You don't have UNKNOWN_PERMISSION
#USER STAT STUFF
  userstats:
    description: Gets yours/a users current stats.
    usage: /<checkstats> [player]
    permission: ComplexProficiencies.misc
    permission-message: You don't have ComplexProficiencies.misc permission
  mystats:
    description: Gets your current stats.
    usage: /<mystats>
    permission: ComplexProficiencies.basic
    permission-message: You don't have ComplexProficiencies.basic permission
  fixexperience:
    description: Updates all current players experience to match that of the leveling system.
    usage: /<fixexperience>
    permission: ComplexProficiencies.levelAdmin
    permission-message: You don't have ComplexProficiencies.levelAdmin permission
  setexperience:
    description: Sets the experience of a player.
    usage: /<setexperience> [player] [Amount]
    permission: ComplexProficiencies.levelAdmin
    permission-message: You don't have ComplexProficiencies.levelAdmin permission
  setlevel:
    description: Sets the level of a player.
    usage: /<setlevel> [player] [Amount]
    permission: ComplexProficiencies.levelAdmin
    permission-message: You don't have ComplexProficiencies.levelAdmin permission
  addexperience:
    description: Adds experience to the select player.
    usage: /<addexperience> [player] [Amount]
    permission: ComplexProficiencies.levelAdmin
    permission-message: You don't have ComplexProficiencies.levelAdmin permission